### PR TITLE
Add Dante Labs

### PR DESCRIPTION
**Pull request by olso**

### CODE REVIEW

**Comment by markwk** [comment]
@olso be great if your description offer a bit more info or context. Admittedly we haven't done a great job so far on all of these, but be better if it shared more on the tech, the special sauce or analysis sophiistication or something. Just a thought. Thanks for contributing.

**Comment by olso** [comment]
@markwk Would "copying" few lines out of https://golden.com/wiki/Dante_Labs work for you?

**Comment by markwk** [comment]
@olso yes that's the kinda stuff I'd be looking for. Definitely the right direction. If we want the list to be most helpful, the differences b/t services is important I think.

**Comment by olso** [comment]
@markwk What do you say now?

**Comment by woop** [comment]
This still live @olso @markwk ?

**Pull request closed without merging**
