### PR TITLE
Some small additions and tweaks

### PR DESCRIPTION
**Pull request by markwk**
Great work on this current draft. I added a few minor changes and two additional services I think you'll like.

### CODE REVIEW

**Comment by woop** [comment]
Hi @markwk 

Looks great. Thanks for the contribution.

I have been trying to follow the style guide over  [here](https://github.com/sindresorhus/awesome/blob/master/contributing.md), but I neglected to update the contributing.md for this project. What I missed is that I'd like to stick to [title case](http://titlecapitalization.com/) descriptions for the links. Would you update your PR using that link?

I will update the guidelines so that future contributors are aware of this.

**Comment by markwk** [comment]
Makes sense. Revised my pull request to fix this.

**Comment by markwk** [comment]
Adding a section for Habit Trackers too. Probably could cherry pick this off into a separate pull request. Your call.

**Comment by woop** [comment]
No worries. I've merged it.

**Pull request merged**
