### PR TITLE
added collaborative debate

### PR DESCRIPTION
**Pull request by ran88dom99**

### CODE REVIEW

**Comment by ran88dom99** [comment]
Hey you there boss?

**Comment by woop** [comment]
why would we add this?

**Comment by ran88dom99** [comment]
It should help advise newcomers on whether they should try to SQ or not. Lists the reasons to SQ in outline mindmap format. It lists all the problems of trying and how to solve some.  What criteria do you need?

**Comment by ran88dom99** [comment]
Discussion Title: Everyone Should Health Track - Self Quantify

1. Everyone Should Health Track - Self Quantify
1.1. Con: Health tracking presents privacy concerns. \[[1](https://www.kialo.com/individual-data-privacy-is-necessary-for-a-healthy-society-9339),[2](https://www.kialo.com/personal-data-monetisation-48867),[3](https://www.kialo.com/should-data-trade-be-prohibited-31853)\]
1.1.1. Pro: It is already somewhat dystopian that [employers](https://belitsoft.com/custom-application-development-services/healthcare-software-development/gamification-in-healthcare-just-for-fun-or-has-real-value)(We all know Fitbit as one of the early innovators in the wearables game. However, the company is positioning itself as the go-to device for employers. Fitbit has almost 1.500 corporate wellness program customers including BP, IBM, and Bank of America. Most of them give their employees Fitbit devices to track their workout progress and health habits.) are monitoring their employees' health; it represents a huge encroachment of capitalism into people's personal lives.
1.1.1.1. Pro: Without the ability to access their own data, users have no way of knowing whether it is recorded accurately. This is counterproductive and potentially unfair if they are judged on that data.
1.1.1.1.1. Pro: [Many devices](https://www.kialo.com/many-many-devices-and-apps-do-not-allow-users-access-to-any-of-their-data-in-the-way-that-they-wish-49787.172) for consumer use do not give their users their own data.
1.1.1.2. Pro: Employers should never be entitled to know everything about their employees as this creates an unethical power dynamic.
1.1.1.2.1. Pro: Employers may be able to identify if female employees are trying for a baby or pregnant possibly even before she herself knows. Unscrupulous employers could then pre-emptively dismiss her or pass over her for promotion, which is discriminatory.
1.1.2. Pro: Especially things like [emotion detection](https://en.wikipedia.org/wiki/Emotion_recognition#Automatic) which is being developed.
1.1.2.1. Pro: [Inner Balance](https://www.heartmath.com/tech/) uses heart rate patterns to determine mood and mental wellbeing.
1.1.2.2. Pro: Applicable to interrogation.
1.1.2.2.1. Pro: Automatic recognition system of emotions expressed through the face using machine learning: [Application to police interrogation simulation](https://ieeexplore.ieee.org/document/8734245)(During our work, we developed Automatic recognition system of emotions expressed through the face. This system will be adapted to judicial police interrogation or interviews simulation. This system is based on a functional division: detection and follow-up the face, acquisition of facial expressions starting from video images sequences, and finally, characteristics extraction and emotions expressed recognition. The deep convolution network model is formed primarily on FER2013. It is used to train and validate the model. We use OpenCV library and its implementation of the Viola and Jones algorithm for face detection.).
1.1.2.3. Pro: Many companies are already developing - or have brought to market - wearable emotion detectors including [Empatica Embrace, Moxo, and the Feel wristband](https://www.wareable.com/wearable-tech/wearables-that-track-emotion-7278).
1.1.3. Pro: Evil organization or general AI could use all this data.
1.1.4. Con: Complete guarantee of privacy can be gained by never letting the smartphone connect to the internet. Air gapping.
1.1.4.1. Con: Doctors and researchers would not use it either.
1.1.4.2. Con: Wifi somehow turns on by itself. I need to get one with manual air gap.
1.1.4.3. Con: Some apps and devices demand regular connections to servers online.
1.1.4.4. Con: Giving up data is only absolutely required in a few rare cases \(research, doctor\). Only then must privacy be breached.
1.1.5. Con: User can use many different companies and not let any company aggregate enough data to matter.
1.1.5.1. Con: Unless they merge or sell data to each other or are hacked.
1.1.5.2. Con: User could be hacked.
1.1.6. Pro: -> See discussion #31853: Data-trade should be prohibited.
1.1.7. Con: -> See discussion #48867: Personal data monetisation
1.1.8. Pro: -> See discussion #9339: Protecting individual data privacy is necessary for a healthy society.
1.1.9. Pro: GPS-enabled health trackers like [Strava](https://www.forbes.com/sites/thomasbrewster/2018/01/29/strava-fitness-data-location-privacy-scare/)(The Strava maps light up different routes taken by those in its 27 million users who didn't turn off location sharing. Whilst the information is anonymized, it's possible to piece together the data to reveal details about users' lives.) can reveal details about users' lives.
1.1.9.1. Pro: GPS-enabled health trackers can make it easy to identify [where a person works and lives](https://www.smh.com.au/lifestyle/health-and-wellness/my-running-app-was-telling-everyone-my-location-and-yours-might-be-too-20190729-p52bta.html)(Any app that shares your precise location is dangerous, full stop, let alone one that has routes which are often going to start at your front door, or your place of work," Ms McLean warns, adding that, although the risk of a stranger stalking you on the basis of your fitness routine is "incredibly remote", these apps are the sort of technology used in domestic violence, and can put you at risk of property crime.), and when they are away from home. They can thus be used as tools for burglars and domestic abusers.
1.1.10. Con: Data protection regulation which applies to digital health trackers is growing and improving.
1.1.10.1. Con: In the US, efforts to bring in new regulations targeted at fitness and health apps to encourage developers to be more responsible with sensitive user data have so far been unsuccessful.
1.1.10.1.1. Pro: Some US senators tried and failed to prevent the [sale of private health data](https://protonvpn.com/blog/fitness-apps-are-good-for-your-health-but-often-bad-for-your-privacy/) to employers, mortgage lenders, and insurers.
1.2. Pro: Improve the management of health conditions including subclinical issues doctors cant help with. \[[1](https://mhealth.jmir.org/2021/3/e26528),[2](https://old.reddit.com/r/QuantifiedSelf/comments/lx7286/xpost_twd_tracked_my_mood_for_the_last_two_years/),[3](https://www.nightscoutfoundation.org/)\]
1.2.1. Con: Custom data sources for rare problems, like shaking, often require either custom devices or at least finding and customization of devices.
1.2.2. Pro: Lifestyle choices like Vegetarianism are supported in this way too.
1.2.2.1. Pro: -> See discussion #18242: Vegetarianism is a nutritionally healthy diet.
1.2.3. Pro: Useful to sort through all suggested remedies \(like the flood of diets\) by testing them. \[[1](https://www.kialo.com/does-meditation-lead-to-health-benefits-38009),[2](https://www.kialo.com/what-is-the-best-diet-for-human-health-and-well-being-7121)\]
1.2.3.1. Pro: Many diet plans are costly, so being able to identify which ones work and which ones don't could save people a lot of money.
1.2.3.1.1. Pro: The average cost of a nutritionist in the UK is [£60/hr](https://www.bidvine.com/nutritionist/price-guide).
1.2.3.2. Con: Relies on [users reporting accurately](https://www.kialo.com/people-make-mistakes-when-recording-data-especially-in-self-reporting-and-sometimes-they-forget-or-slack-49787.219).
1.2.4. Con: People often know what they need to do but choose not to because it takes too much effort.
1.2.4.1. Con: Health tracking can be used to motivate people. See [top level pro claim](https://www.kialo.com/it-can-be-used-to-motivate-change-either-through-gamification-or-just-by-showing-the-user-that-they-have-improved-and-it-49787.13).
1.2.4.2. Con: Not if it stops their suffering.
1.3. Pro: Self tracking can be used to motivate change.
1.3.1. Pro: [78%](https://www.healthcareitnews.com/news/science-fiction-real-world-emerging-technologies-poised-disrupt-healthcare)(The move to this futuristic environment, however, appears to be a welcome one – as 78 percent of consumers ages 25 to 34 said they would use some form of gamification in their treatments, according to PwC’s Top Health Industry Issues of 2017 report.2) of people aged 25-34 say they would use gamification as part of a treatment plan.
1.3.2. Pro: [Beeminder](https://www.beeminder.com/) gamifies health goals by converting them into financial incentives; users make a commitment contract and if they don't meet their target, they are charged.
1.3.2.1. Con: A [2014 study](https://www.thelancet.com/journals/landia/article/PIIS2213-8587\(16\)30284-4/fulltext)(The cash incentive was most effective at increasing MVPA bout min per week at 6 months, but this effect was not sustained 6 months after the incentives were discontinued.) found that even with financial incentives, health trackers did not improve the participants' health and fitness after a 6 month period.
1.3.3. Pro: In many cases just by showing the user that they have improved and it is recorded.\[[3](https://old.reddit.com/r/QuantifiedSelf/comments/lv2ykt/xpost_tracking_my_pushups_in_2020_my_new_years/)\]
1.3.4. Pro: Gamification. \[[1](https://en.wikipedia.org/wiki/Gamification)(employs game design elements\[4\]\[2\]\[5\]\[6\]\[3\] to improve user engagement,\[7\]\[8\]\[9\] organizational productivity,\[10\] flow,\[11\]\[12\] learning,\[13\]\[14\] crowdsourcing,\[15\] knowledge retention,\[16\] employee recruitment and evaluation, ease of use, usefulness of systems,\[12\]\[17\]\[18\] physical exercise,\[19\] traffic violations,\[20\] voter apathy,\[21\]\[22\] public attitudes about alternative energy,\[23\]),[2](https://habitica.com/)(Habitica is a free habit-building and productivity app that treats your real life like a game. With in-game rewards and punishments to motivate you and a strong social network to inspire you, Habitica can help you achieve your goals to become healthy, hard-working, and happy.),[3](https://ieeexplore.ieee.org/abstract/document/6758978),[4](https://www.sciencedirect.com/science/article/abs/pii/S1071581914001256),[5](https://www.researchgate.net/publication/277331055_Gaming_the_Quantified_Self)\]
1.3.4.1. Pro: Health trackers can keep people motivated with additional functionalities like badges, challenges, and daily goals. Therefore, they improve health management by both monitoring as well as motivating.
1.3.4.2. Con: A 2014 analysis of 132 health and fitness apps revealed that many of their gamification elements were [not based on behavioral theory](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4307823/)(This shows a lack of integrating important elements of behavioral theory from the app industry, which can potentially impact the efficacy of gamification apps to change behavior.). As such, it is not clear how successful gamification is in practice.
1.3.4.2.1. Con: It is possible that health and fitness apps have improved considerably since 2014, so this study's findings are not necessarily applicable any more.
1.3.5. Con: Changing one's health and fitness involves commitment. Yet a [2020 study](https://link.springer.com/article/10.1007/s00779-020-01453-9)(An analysis of the survey data indicates that commitment to self-tracking positively correlates with autonomous motivation for tracking and negatively correlates with controlled motivation.) found that commitment to self-tracking negatively correlates with controlled motivation, such as that used by health tracker apps.
1.3.6. Pro: Tracking things like your health also helps to build [healthy habits](https://newsinhealth.nih.gov/2018/03/creating-healthy-habits)(Lots of things you do impact your health and quality of life, now and in the future. You can reduce your risk for the most common, costly, and preventable health problems—such as heart disease, stroke, cancer, type 2 diabetes, and obesity—by making healthy choices.), which is beneficial for multiple aspects of one's life.
1.3.7. Pro: What people think of as willpower is still brain chemistry and manipulable easily by outside factors. Tracking those factors could find solution to problems thought by them too difficult.
1.3.8. Pro: Most consumer focused health tracking wearables include lots of motivating information. \[[1](https://blog.fitbit.com/challenges/),[2](https://www.cnet.com/reviews/xiaomi-mi-band-2-review/2/)\]
1.3.9. Pro: gamification is only one of the known behavior change techniques; techniques most suitable for behavior change to the user profile shall be leveraged for behavior change. -katwac
1.3.9.1. Pro: Self tracking can help determine which behavior change technique is best.
1.4. Pro: Quantification supports introspection and deliberate planning of one's life.
1.4.1. Con: The need to plan out one's life can itself be a stressor and, as such, something to be avoided.
1.5. Con: Choosing, setting up, and connecting user's selection of apps and devices can be quite a bit of work. Or expensive. Only when new devices or apps are introduced not the daily effort of tracking.
1.5.1. Pro: Many many devices and apps do not allow users access to any of their data in the way that they wish; \(raw,programmatically,easily\).
1.5.1.1. Pro: Apps and devices often give aggregate data instead of raw detailed data. Users may need raw detailed data.
1.5.1.1.1. Pro: Raw, detailed data is more useful than processed, aggregate data.
1.5.1.1.1.1. Con: Processing raw data usually requires a good program of its own, often unavailable.
1.5.1.1.1.2. Con: The raw data may not always bee needed we can see significant changes in trends \(months\) from processed data. -katewac \[[1](https://pubmed.ncbi.nlm.nih.gov/33142665/)\]
1.5.1.1.1.3. Pro: Some amount of information is always lost in summation.
1.5.1.1.1.3.1. Pro: Self quantifiers usually explore. For exploration any data is useful. This includes data that shows that something interesting did not happen.
1.5.1.2. Pro: [Few apps](https://terpconnect.umd.edu/~choe/download/JAMIA-2019-Kim-DataAccessibility.pdf) provide complete data access. Possibly, [few provide any access](https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/QXMY88).
1.5.1.3. Con: The [California Consumer Privacy Act \(CCPA\)](https://oag.ca.gov/privacy/ccpa) gives California residents the right to access their data.
1.5.1.4. Pro: Self trackers always want devices and apps that give their data easily and programmatically.
1.5.1.4.1. Pro: In addition, his problem is rarely identified easily, increasing the time needed to search for a device or app.
1.5.1.4.2. Con: Sometimes users choose to manually enter data, that could be received programmatically, into a text file. If the data is slow or sparse, self quantifier could write it down into a text file.
1.5.1.4.2.1. Con: Manually entering data \(that could be obtained programmatically\) always increases daily average time spent tracking at least a little, and possible a great amount!
1.5.1.5. Con: EU’s General Data Protection Regulation \(GDPR\) has forced companies operating in Europe to give users any of their data they request. \[[1](https://www.kialo.com/collected-data-which-used-to-be-closed-off-to-consumers-is-useful-for-health-tracking-for-n-of-1-studies-25580.178)\]
1.5.1.6. Con: Open source software and hack hobby devices always allow users access to all their data.
1.5.2. Pro: Self trackers may have privacy concerns \[[top claim](https://www.kialo.com/also-privacy-concerns-\[123\]-49787.103)\] that would invalidate options.
1.5.3. Pro: Emotion detectors like the Amazon Halo are [not designed or authorized for medical purposes](https://www.theverge.com/2020/8/27/21402493/amazon-halo-band-health-fitness-body-scan-tone-emotion-activity-sleep), so cannot be relied on as such.
1.5.4. Pro: -> See 1.2.1.
1.5.5. Pro: The quality of data produced by devices can be quite terrible. Often device manufacturers do not like user to worry about sensors not connecting to body properly. Sometimes all the user really sees is guesswork.
1.5.5.1. Pro: This causes or is caused by devices developers [not allowing access to data. \[claim\]](https://www.kialo.com/many-many-devices-and-apps-do-not-allow-users-access-to-any-of-their-data-in-the-way-that-they-wish-49787.172)
1.5.5.2. Con: Mitigate by comparing to well tested standard or non continuous, more expensive devices. Sometimes a simple correction is all that is needed. Such comparison may become automatic.
1.5.6. Con: You can follow someone else's previously made trail \(selection of devices\) called a "stack". \[[1](https://github.com/ran88dom99/QS-data-flow-network-graph),[2](https://github.com/woop/awesome-quantified-self),[3](https://quantifiedself.com/show-and-tell/)\]
1.5.6.1. Con: This will not work for pioneering. For example: rare problems.
1.6. Con: It takes too much time and effort every day. -sv
1.6.1. Pro: -> See 1.5.1.4.2.1.
1.6.2. Pro: Around [a third of people](https://www.wired.com/story/science-says-fitness-trackers-dont-work-wear-one-anyway/)(About one third of people who buy fitness trackers stop using them within six months, and more than half eventually abandon them altogether.) who purchase fitness trackers stop using them within 6 months and half eventually abandon them. This indicates that their capacity to motivate is easily outstripped by other factors.
1.6.3. Pro: Some amount of manual entry is absolutely unavoidable.
1.6.3.1. Pro: People complain about remembering five minutes a day. -qs meetup
1.6.3.1.1. Con: Once it becomes habit it wont be hard according to self help books.
1.6.3.1.1.1. Con: Even if it becomes a habit, we need to scientifically asses the data for response shift, i.e., changes in self report over time. \[[1](https://journals.sagepub.com/doi/abs/10.1177/0193841X8000400105)\] -katewac
1.6.4. Con: Many devices and apps are almost completely automatic and require just a few minutes a month of user's time. Ex. Fitness watches are quite popular. \[[1](https://play.google.com/store/apps/collection/promotion_3000e6f_googlefit_all),[2](https://activitywatch.net/)\]
1.6.4.1. Pro: Research shows that patients successfully engaged with a wearable/health app take less than five minutes a day; most of the behavior assessment wrt activity and sleep is automatic. -katewac \[[1](https://www.frontiersin.org/articles/10.3389/fpsyg.2019.02388/full)\]
1.6.5. Con: Testing and manual data entry for QS can overlap with other daily activities. Ex. Studying and cognitive testing via anki. Plan meals and shopping and record nutritional info at the same time. \[[1](https://ankiweb.net/shared/info/1591779596),[2](https://apps.apple.com/us/app/eat-this-much-meal-planner/id981637806)\]
1.6.5.1. Con: Many users will not have found these tools and activities too useful before choosing to health track.
1.7. Con: People make mistakes when recording data, especially in self reporting. And sometimes they forget or slack. This claim is often the other side of "it takes lots of time" as a user can slack or not. Similarly affects pros Research, Optimization and Managing Health.
1.7.1. Pro: Using health trackers to monitor and try out different diets relies on people reliably and accurately recording what they consume. This is often hard to do and so much of the personalised dietary advice provided may be unreliable.
1.7.1.1. Pro: If one eats out at a restaurant or orders a takeaway, it is not always clear what all the ingredients are or their calorific content.
1.7.1.1.1. Con: Large restaurant chains are required to have detailed nutrition information. It can be found online if not in store.
1.7.1.2. Con: So long as user over and under estimates in about equal proportions it becomes a matter of statistics. Mismeasurement would be normal - Gaussian distributed without bias \(systematic imbalance of mismeasurement\) .
1.7.1.2.1. Con: While inaccurate calorie estimations may cancel each other other, there is no reliable way of confirming whether this is the case.
1.7.1.2.1.1. Con: User could have some third party check their measurements without telling them. If error is normal then everything is fine.
1.7.1.2.2. Con: Bias is pretty common. \[[Here is the top level category.](https://www.kialo.com/people-make-mistakes-when-recording-data-especially-in-self-reporting-and-sometimes-they-forget-or-slack-this-claim-is-49787.219?path=49787.0~49787.3-49787.219&active=-49787.219&action=comments)\]
1.7.1.2.2.1. Con: It may be a diet's job to prevent user from falling into several of these systematic mis measurements.
1.7.1.3. Pro: Numerous studies show that people [consistently underestimate](https://coach.nine.com.au/diet/estimating-calories-weight-gain/899ff052-a13c-4694-9ac3-91f6d20c291e) their calorie intake, often significantly so.
1.7.1.4. Pro: Nutritional information on food labels can be inaccurate since food companies are allowed a [20% error margin](https://www.fda.gov/regulatory-information/search-fda-guidance-documents/guidance-industry-guide-developing-and-using-data-bases-nutrition-labeling)(...the label is considered to be out of compliance if the nutrient content of a composite of the product is greater than 20% above the value declared on the label.).
1.7.2. Con: many sources do not rely on self assessment never mind input
1.7.3. Pro: forgot
1.8. Con: Somethings people do not want to know. Like genetic predisposition to Alzheimer. -MB \[[1](https://link.springer.com/article/10.1007/s12687-017-0310-z),[2](https://pubmed.ncbi.nlm.nih.gov/22004015/)\]
1.8.1. Con: This applies to few types of data.
1.8.2. Con: There may be cures in the works. -J
1.9. Con: Either the analysis of QS data is very difficult or at least no good algorithms are available. It may be difficult to get complicated info like even correlation out of the data. This issue and all arguments under it apply mostly to some pro self tracking arguments. Ex; self optimization, health tracking, and, to a lesser degree, usefulness for research.
1.9.1. Pro: Insights gained from self-tracking are rarely novel and actionable.
1.9.1.1. Con: We just have not found those examples. Requires self-tracker knowledge or skills in complex tasks and interpretations to make sense of data. Therefore, even if successfully going through that effort, the next one for disseminating online, sharing with peers or \(few cases so far\) publishing on journals, seems considerable, I wonder how to quantify or get to know how many successful self-tracking uses solving a personal problem are unknown \(I mean "below the radars"\).
1.9.2. Pro: The formulas used to calculate calorie intake such as MyFitnessPal are not as accurate for [people of color or those with a high BMI](https://www.rachaelhartleynutrition.com/blog/why-you-should-delete-your-myfitnesspal-app)(These formulas were developed through research in not very diverse groups, and therefore are less accurate for people of color and higher weight individuals.).
1.9.2.1. Pro: One such formula - [the Mifflin St. Jeor equation](https://www.clinicalnutritionjournal.com/article/S0261-5614\(13\)00100-3/fulltext)(Accuracy rate was lower in obese than non-obese volunteers, no matter which equation was used \(for example 87 vs. 75% for the Mifflin St. Jeor equation\).) - has an accuracy rate of 75% compared to 87% for obese and non-obese people, respectively.
1.10. Pro: Life logging. It can be fun to just reminisce.
1.10.1. Pro: If you get a personal best on a run and upload a picture of yourself alongside the stats from it, this can be a nice memory to return to.
1.11. Pro: Contribute your medical data to research. \[[1](http://openhumans.org),[2](https://www.apple.com/newsroom/2019/03/stanford-medicine-announces-results-of-unprecedented-apple-heart-study/),[3](https://www.joinallofus.org/)\]
1.11.1. Con: Many trackers marketed as "health trackers", such as the Amazon Halo, are not accredited medical devices. \[[see claim](https://www.kialo.com/emotion-detectors-like-the-amazon-halo-are-not-designed-or-authorized-for-medical-purposes-so-cannot-be-relied-on-as-49787.263)\]
1.11.2. Pro: 12 self experimenters [won Nobel prizes](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3298919/)(It turns out that 12 actually received one type of Nobel Prize or another, the most recent one going to Barry Marshall in 2005 after his ingestion of a Helicobacter culture to demonstrate in his own stomach how it might cause gastrointestinal disease \(Table II\).).
1.11.2.1. Con: Though self-experimentation is more broad than self tracking.
1.11.3. Pro: There's a wide literature showing the validity of N-of-1 approaches, with successful protocols and empirical insights. For example with a quick check in google scholar for patient-led studies and similar ones. -esenabre \[[1](https://scholar.google.com/scholar?hl=es&as_sdt=0,5&q=n-of-1+patient-led&btnG=)\]
1.11.4. Con: -> See 1.1.4.4.
1.11.5. Pro: Current dietary studies are constantly ridiculed and for good reason. Thorough health tracking is as almost as good as an RCT. \[[1](https://old.reddit.com/r/ScientificNutrition/comments/g3nevh/legumes_the_most_important_dietary_predictor_of/fnuuhm5/),[2](https://www.reddit.com/r/nutrition/comments/38q90m/why_is_there_so_much_disagreement_in_nutrition/),[3](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3118090/)\]
1.12. Pro: Optimize health, productivity, education, sports training, and cognitive functioning. \[[1](https://forum.quantifiedself.com/t/your-most-impactful-experiments/9031/4),[2](https://old.reddit.com/r/QuantifiedSelf/comments/bf73ql/i_tracked_everything_i_ate_for_the_last_year/),[3](https://dailyvis.com/posts/self-analysis-with-my-quantified-self-data/),[4](https://memory.ai/timely-blog/quantifying-productivity)\]
1.12.1. Pro: Professionals use this idea, especially coaches of athletes.
1.12.1.1. Pro: [Sir Dave optimized everything in tiny 1% increments to bring UK the gold.](https://hbr.org/2015/10/how-1-performance-improvements-led-to-olympic-gold)(We were precise about food preparation. We brought our own mattresses and pillows so our athletes could sleep in the same posture every night. We searched for small improvements everywhere and found countless opportunities. Taken together, we felt they gave us a competitive advantage.)
1.12.1.2. Con: Most people are not athletes and do not need or want to be in order to be reasonably healthy.
1.12.1.3. Pro: [SY writes of two books about businesses using metrics.](https://www.scotthyoung.com/blog/2021/07/19/metrics-useful-or-evil/) This is evidence that the idea is pretty common.
1.12.2. Pro: This would increase the progress rate of humanity by increasing well being and potential of individuals. -camelsoft
1.12.3. Con: But it can create a certain society of control and performance where everything and everyone is constantly quantified, measured and controlled. -simon_fort \[[1](https://www.jstor.org/stable/778828?seq=1),[2](https://en.arguman.org/xyz-corp-should-implement-their-health-monitoring-program)\]
1.12.3.1. Con: SY writes that The Tyranny of Metrics states that as soon as something is measured [the underlings try to game the system.](https://www.scotthyoung.com/blog/2021/07/19/metrics-useful-or-evil/)
1.12.3.2. Con: The original premise is about self quantification and not about a central entity enforcing bars for everyone to reach. It meas everyone can set their goals themselves and quantification aspects helps reaching them. -camelsoft
1.12.3.2.1. Con: Central entity is not necessarily a company that forces us to quantify ourselves, but it can be a simple desire to conform to the performance society. The simple fact of quantifying oneself in order to improve one's productivity makes me think of a "self" -disciplinary society, a society of control. -simon-fort

**Comment by ran88dom99** [comment]
If you will not accept this suggestion I will start my own 'awesome' list.

**Pull request closed without merging**
