### PR TITLE
Move shutdown, EveryMove acquired by Higi

### PR DESCRIPTION
**Pull request by o1xhack**
Hi, we need a way to mark a service/app shutdown in the future cause lots of might dead. I just mark Move first cause it's already shutdown for a long time
- Marked Move as service shutdown
- add EveryMove acquired by Higi and no longer exist

### CODE REVIEW

**Comment by woop** [comment]
Perhaps better to completely remove?

**Comment by o1xhack** [comment]
@woop Perhaps give a section for the dead service? I think all dead service is still a contribution and it's good to have a place memorize them!

**Comment by woop** [comment]
> @woop Perhaps give a section for the dead service? I think all dead service is still a contribution and it's good to have a place memorize them!

Not sure about the utility of that. They are historically stored in the git log already. Alternatively we could have a different markdown doc (not the README).

**Comment by o1xhack** [comment]
@woop This makes sense. Let's create a new doc and move the dead service to there. Do you want to create a new doc and reject this pull request? Then I can do a new one after the new doc created.

**Comment by woop** [comment]
@o1xhack Missed this comment. My bad. Can you submit a PR for a new doc? Maybe ARCHIVED.md?

**Pull request closed without merging**
