### PR TITLE
Add Conjure

### PR DESCRIPTION
**Pull request by Whelton**
Added [Conjure.so](https://conjure.so) to what I believe are the relevant categories.
Happy to alter if felt not applicable to some.
Thank you!

### CODE REVIEW

**Comment by woop** [comment]
Please choose one category

**Comment by Whelton** [comment]
@woop I've done this now, thank you!

**Comment by Whelton** [comment]
@woop I’ve updated this, this ok? Thank you!

**Review by Ro113R — COMMENTED** [review]
Devuelta

**Pull request merged**
